const yearData = [
	{
	  month: 'January', 
        weeks: [1, 2, 3, 4, 5],
        days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []},
            {day: 31, events: []}
          ]
	},
	{
	  month: 'February', 
	  weeks: [5, 6, 7, 8, 9],
        days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []}
          ] 
	},
	{
	  month: 'March', 
	  weeks: [9, 10, 11, 12, 13, 14],
        days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []},
            {day: 31, events: []}
          ] 
	},
      { 
          month: 'April', 
          weeks: [14, 15, 16, 17, 18],
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []}
          ] 
        },
        { 
          month: 'May',
          weeks: [18, 19, 20, 21, 22], 
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []},
            {day: 31, events: []}
          ] 
        },
        { 
          month: 'June',
          weeks: [22, 23, 24, 25, 26, 27], 
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []}
          ] 
        },
         {
          month: 'July', 
          weeks: [27, 28, 29, 30, 31], 
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []},
            {day: 31, events: []}
          ] 
        },
        { 
          month: 'August', 
          weeks: [31, 32, 33, 34, 35], 
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []},
            {day: 31, events: []}
          ] 
        },
        { 
          month: 'September', 
          weeks: [36, 37, 38, 39, 40], 
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []}
          ] 
        },
        { 
          month: 'October',
          weeks: [40, 41, 42, 43, 44],  
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []},
            {day: 31, events: []}
          ] 
        },
        { 
          month: 'November', 
          weeks: [44, 45, 46, 47, 48], 
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []}
          ] 
        },
        { 
          month: 'December', 
          weeks: [49, 50, 51, 52, 1], 
          days: [
            {day: 1, events: []},
            {day: 2, events: []},
            {day: 3, events: []},
            {day: 4, events: []},
            {day: 5, events: []},
            {day: 6, events: []},
            {day: 7, events: []},
            {day: 8, events: []},
            {day: 9, events: []},
            {day: 10, events: []},
            {day: 11, events: []},
            {day: 12, events: []},
            {day: 13, events: []},
            {day: 14, events: []},
            {day: 15, events: []},
            {day: 16, events: []},
            {day: 17, events: []},
            {day: 18, events: []},
            {day: 19, events: []},
            {day: 20, events: []},
            {day: 21, events: []},
            {day: 22, events: []},
            {day: 23, events: []},
            {day: 24, events: []},
            {day: 25, events: []},
            {day: 26, events: []},
            {day: 27, events: []},
            {day: 28, events: []},
            {day: 29, events: []},
            {day: 30, events: []},
            {day: 31, events: []},
          ],
        }

]

export { yearData as default };